### ISSUE TITLE
Where to find dependency classes?

### ISSUE THREAD

**Issue by eder7** [HubSpot/ChromeDevToolsClient#9]
Hey,
thanks for this nice library. It worked out nice for me but after a while I faced some problem which I tried to solve in a pull request. It seems that some dependencies like `com.hubspot.chrome.devtools.client.core.cachestorage.CacheStorage` (as an example) and more are missing. The compiler can't find the definition of that class, and when I searche for it on GitHub I also can't find it. Actually, most of the imports in `ChromeDevToolsSession` are red in my IDE. Can you please give me a hint?
All the best!

**Comment by ssalinas** [comment]
Hi @eder7 , these classes are actually automatically generated from the chrome devtools protocol spec (a big json file). If you build the project with maven, it has hooks that generate these classes. You'll notice they appear in the target folder after something like a `mvn clean package`. Some IDEs will pick it up after seeing this, others you need to explicitly tell the IDE where the classes are
